import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <div className="">
            <p>Bens Portfolio</p>
          </div>
          <div className="navRight">
            <Link href="/"> Home</Link>
            <Link href="/Apex"> About Apex</Link>
            <Link href="/mysport"> My Sport</Link>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
